app_one/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from app_one.views import *

app_name = "app_one"

urlpatterns = [
    path("", IndexView.as_view(), name="home"),
    path("currency/", view_currency, name="currency"),
    path("get-currency/", get_currency, name="get_currency"),

    path('login/', auth_views.LoginView.as_view(template_name='app_one/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path("register/", RegisterView.as_view(), name="register"),
]

htmx_urlpatters = [
    path("check-username/", check_username, name='check-username'),
]

urlpatterns += htmx_urlpatters

test_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app_one.urls", "app_one")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_one/models.py
from django.db import models

# Create your models here.

app_one/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

app_one/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import FormView, TemplateView
from random import randint
from django.shortcuts import render

from app_one.forms import RegisterForm

# Create your views here.


class IndexView(TemplateView):
    template_name = 'app_one/index.html'


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'app_one/register.html'
    success_url = reverse_lazy('app_one:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def check_username(request):
    username = request.POST.get('username')
    if get_user_model().objects.filter(username=username).exists():
        return HttpResponse("<div id='username-error' class='error'>This username already exists</div>")
    else:
        return HttpResponse("<div id='username-error' class='success'>This username is available</div>")


def view_currency(request):
    return render(request, 'app_one/currency.html')


def get_currency(request):
    return render(request, 'app_one/partials/content.html', {"USD": randint(10, 100), "ERO": randint(10, 100), "BDT": randint(99, 200)})

templates/app_one/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HTMX Test App</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom CSS -->

    <!-- jQuery and Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.6.0"></script>
</head>
<body>
    {% include 'app_one/partials/navbar.html' %}

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

templates/app_one/currency.html
{% extends 'app_one/base.html' %}

{% block content %}


<div id="currency" hx-get="/get-currency/" hx-trigger="every 2s" hx-swap="innerhtml">

  {% include 'app_one/partials/content.html' %}

</div>


{% endblock content %}

templates/app_one/index.html
{% extends 'app_one/base.html' %}

{% block content %}

<p>Welcome!</p>

{% lorem 2 p %}

{% endblock content %}

templates/app_one/login.html
{% extends 'app_one/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="align-center col-8 offset-2">
    <p class="lead mb-3 ml-0">Login</p>
    <hr/>
    <form method="POST" action="{% url 'app_one:login' %}" autocomplete="off">
        {% csrf_token %}

        {% for field in form %}
        <div class="form-group mb-3">
            <label>{{ field.label_tag }}</label>
            {{ field.errors }}
            {% render_field field class="form-control" placeholder=field.name %}
        </div>
        {% endfor %}
        
        <button type="submit" class="btn btn-success mt-2">Login</button>
    </form>
</div>

{% endblock content %}

templates/app_one/partials/content.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">DOLLAR</th>
        <th scope="col">EURO</th>
        <th scope="col">TAKA</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ USD }} $</td>
        <td>{{ ERO }} €</td>
        <td>{{ BDT }} ৳</td>
      </tr>
    </tbody>
</table>

templates/app_one/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'app_one:home' %}">Test App</a>

    <div id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app_one:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app_one:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app_one:register' %}">Register</a>
            </li>
            {% endif %}

            <li class="nav-item">
                <a class="nav-link" href="{% url 'app_one:currency' %}">currency</a>
            </li>

        </ul>
    </div>
</nav>

templates/app_one/register.html
{% extends 'app_one/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="align-center col-8 offset-2">
    <p class="lead mb-3 ml-0">Register</p>
    <hr/>
    <form method="POST" action="{% url 'app_one:register' %}" autocomplete='off'>
        {% csrf_token %}

        <div class="form-group mb-3">
            <label>{{ form.username.label_tag }}</label>
            {{ form.username.errors }}
            {% render_field form.username hx-post="/check-username/" hx-swap="outerhtml" hx-target="#username-error" hx-trigger="keyup changed" class="form-control" %}
            <div id="username-error"></div>
        </div>
        <div>

            <label>{{ form.password1.label_tag }}</label>
            {{ form.password1.errors }}
            {% render_field form.password1 class="form-control" %}
        </div>
        <div>
            <label>{{ form.password2.label_tag }}</label>
            {{ form.password2.errors }}
            {% render_field form.password2 class="form-control" %}
        </div>
        
        <button type="submit" class="btn btn-success mt-2">Register</button>
    </form>
</div>
{% endblock content %}